package org.zirbes.rxjava

import groovy.transform.CompileStatic

@CompileStatic
class BirdType {

    static final List<String> BIRD_TYPES = [
        "Double Crested Cormorant",
        "Great Blue Heron",
        "Great Egret",
        "Mute Swan",
        "Canada Goose",
        "Mallard",
        "Turkey Vulture",
        "Osprey",
        "Bald Eagle",
        "Sharp-Shinned Hawk",
        "Red-Tailed Hawk",
        "American Kestrel",
        "Peregrine Falcon",
        "Wild Turkey",
        "Killdeer",
        "Sanderling",
        "Laughing Gull",
        "Herring Gull",
        "Common Tern",
        "Rock Dove",
        "Mourning Dove",
        "Great Horned Owl",
        "Eastern Screech Owl",
        "Downy Woodpecker",
        "Red-Bellied Woodpecker",
        "Northern Flicker",
        "Tree Swallow",
        "Blue Jay",
        "American Crow",
        "Black-capped Chickadee",
        "Tufted Titmouse",
        "Eastern Bluebird",
        "American Robin",
        "Gray Catbird",
        "Northern Mockingbird",
        "Red-Eyed Vireo",
        "Yellow-rumped Warbler",
        "Northern Mockingbird",
        "Northern Cardinal",
        "White-Throated sparrow",
        "Song Sparrow",
        "Dark-Eyed Junco",
        "Red-Winged Blackbird",
        "Common Grackle",
        "House Finch",
        "American Goldfinch",
        "House Sparrow",
        "European Starling",
        "Canada Goose",
        "Red-tailed Hawk",
        "American Kestrel",
        "Great Horned Owl (evening, early morning)",
        "Barred Owl (evening, early morning)",
        "Mourning Dove",
        "Belted Kingfisher",
        "Red-headed Woodpecker",
        "Northern (Yellow-shafted) Flicker",
        "Red-bellied Woodpecker",
        "Downy Woodpecker",
        "Common Crow",
        "Blue Jay",
        "Black-capped Chickadee",
        "Tufted Titmouse",
        "White-breasted Nuthatch",
        "Brown Creeper",
        "Robin",
        "Cedar Waxwing",
        "Brown-headed Cowbird",
        "Red-winged Blackbird",
        "Common Grackle",
        "Eastern Meadowlark",
        "Starling",
        "House (English) Sparrow",
        "Cardinal",
        "House Finch",
        "American Goldfinch",
        "Song Sparrow",
        "Wood Duck",
        "Great Blue Heron",
        "Green Heron",
        "Killdeer",
        "Turkey Vulture",
        "Yellow-billed Cuckoo",
        "Common Nighthawk",
        "Eastern Kingbird",
        "Eastern Phoebe",
        "Eastern Pewee",
        "Purple Martin",
        "Barn Swallow",
        "Chimney Swift",
        "House Wren",
        "Brown Thrasher",
        "Catbird",
        "Eastern Bluebird",
        "American Redstart",
        "Yellow Warbler",
        "Common Yellowthroat",
        "Northern (Baltimore) Oriole",
        "Indigo Bunting",
        "Rose-Breasted Grosbeak",
        "Chipping Sparrow",
        "Pacific Loon",
        "Western Grebe",
        "Brown Pelican",
        "Double-crested Cormorant",
        "Brandt's Cormorant",
        "Mallard",
        "Surf Scoter",
        "Red-shouldered Hawk",
        "Red-tailed Hawk",
        "California Quail",
        "American Coot",
        "Killdeer",
        "Black-necked Stilt",
        "American Avocet",
        "Willet",
        "Marbled Godwit",
        "Western Sandpiper",
        "Least Sandpiper",
        "Heermann's Gull",
        "California Gull",
        "Western Gull",
        "Glaucous-winged Gull",
        "Forster's Tern",
        "Rock Dove",
        "Mourning Dove",
        "Anna's Hummingbird",
        "Black Phoebe",
        "Western Kingbird",
        "Western Scrub-Jay",
        "American Crow",
        "Common Raven",
        "Cliff Swallow",
        "Chestnut-backed Chickadee",
        "Bushtit",
        "Pygmy Nuthatch",
        "Bewick's Wren",
        "Ruby-crowned Kinglet",
        "American Robin",
        "European Starling",
        "Yellow Warbler",
        "Yellow-rumped Warbler",
        "Townsend's Warbler",
        "Wilson's Warbler",
        "Western Tanager",
        "California Towhee",
        "Song Sparrow",
        "White-crowned Sparrow",
        "Dark-eyed Junco",
        "Brewer's Blackbird",
        "House Finch",
        "Lesser Goldfinch",
        "House Sparrow"
    ]

    static String name(int i) {
        int bird = i % BIRD_TYPES.size()
        BIRD_TYPES[bird]
    }

    static String type(int i) {
        name(i).split(' ')[-1]
    }

}
