package org.zirbes.rxjava

import groovy.transform.CompileStatic

@CompileStatic
class BirdType {

    static final List<String> NON_PASSERINES = [
        "Elegant crested tinamou",
        "Little tinamou",
        "Slaty-breasted tinamou",
        "Thicket tinamou",
        "Great tinamou",
        "Chilean tinamou",
        "Cinereous tinamou",
        "Brown tinamou",
        "Common ostrich",
        "Greater rhea",
        "Southern cassowary",
        "Dwarf cassowary",
        "Emu",
        "Brown kiwi",
        "Little spotted kiwi",
        "A willow ptarmigan in Alaska",
        "Australian brush turkey",
        "Malleefowl",
        "Maleo",
        "Plain chachalaca",
        "Yellow-knobbed curassow",
        "Horned guan",
        "Crested guan",
        "Dusky-legged guan",
        "Helmeted guineafowl",
        "Vulturine guineafowl",
        "California quail",
        "Northern bobwhite",
        "Wild turkey",
        "Ruffed grouse",
        "Montezuma quail",
        "Spruce grouse",
        "Hazel grouse",
        "Western capercaillie",
        "Sage-grouse",
        "Rock ptarmigan",
        "Willow ptarmigan",
        "Himalayan snowcock",
        "Chukar partridge",
        "Cape spurfowl",
        "Grey partridge",
        "Jungle bush quail",
        "Common quail",
        "Crested partridge",
        "Hill partridge",
        "Blyth's tragopan",
        "Satyr tragopan",
        "Temminck's tragopan",
        "Blood pheasant",
        "Himalayan monal",
        "Great argus",
        "Red junglefowl",
        "Green junglefowl",
        "Ceylon junglefowl",
        "Chicken",
        "Common pheasant",
        "Elliot's pheasant",
        "Golden pheasant",
        "Green pheasant",
        "Indian peafowl",
        "Palawan peacock-pheasant",
        "Congo peafowl",
        "Southern screamer",
        "Horned screamer",
        "Magpie-goose",
        "Swan goose",
        "White-faced whistling duck",
        "Greater white-fronted goose",
        "Greylag goose",
        "Bar-headed goose",
        "Snow goose",
        "Nene",
        "Canada goose",
        "Brent goose (brant)",
        "Barnacle goose",
        "Canada goose",
        "Cackling goose",
        "Red-breasted goose",
        "Hawaiian goose",
        "Woods-walking goose",
        "Black swan",
        "Mute swan",
        "Whooper swan",
        "Tundra swan",
        "Magellanic flightless steamer duck",
        "Spur-winged goose",
        "Egyptian goose",
        "Blue duck",
        "Orinoco goose",
        "Andean goose",
        "African pygmy goose",
        "Common shelduck",
        "Pink-eared duck",
        "Muscovy duck",
        "Wood duck",
        "Mandarin duck",
        "Gadwall",
        "American wigeon",
        "Mallard",
        "Northern shoveler",
        "Brown teal",
        "Northern pintail",
        "Common teal",
        "Marbled duck",
        "Common pochard",
        "Tufted duck",
        "Greater scaup",
        "King eider",
        "Harlequin duck",
        "Black scoter",
        "Long-tailed duck",
        "Common goldeneye",
        "Smew",
        "Common merganser",
        "Black-headed duck",
        "Ruddy duck",
        "Musk duck",
        "Emperor penguin",
        "King penguin",
        "Gentoo penguin",
        "Adelie penguin",
        "Rockhopper penguin",
        "Macaroni penguin",
        "Yellow-eyed penguin",
        "Fairy penguin",
        "African penguin",
        "Magellanic penguin",
        "Galápagos penguin",
        "Chinstrap penguin",
        "Erect-crested penguin",
        "Humboldt penguin",
        "Royal penguin",
        "Black-throated diver",
        "Sooty albatross",
        "Black-browed albatross",
        "Laysan albatross",
        "Royal albatross",
        "Wandering albatross",
        "Southern giant petrel",
        "Antarctic petrel",
        "Northern fulmar",
        "Snow petrel",
        "Fairy prion",
        "Cook's petrel",
        "Antarctic prion",
        "Cahow",
        "Cape petrel",
        "Cory's shearwater",
        "Sooty shearwater",
        "Short-tailed shearwater",
        "Manx shearwater",
        "Wilson's storm petrel",
        "European storm petrel",
        "Common diving petrel",
        "Black-bellied storm petrel",
        "Ashy storm petrel",
        "Leach's storm petrel",
        "Little grebe",
        "Australasian grebe",
        "White-tufted grebe",
        "Hoary-headed grebe",
        "Clark's grebe",
        "Great crested grebe",
        "Greater flamingo",
        "Lesser flamingo",
        "Andean flamingo",
        "Chilean flamingo",
        "Wood stork",
        "African openbill",
        "Yellow-billed stork",
        "Saddle-billed stork",
        "White stork",
        "Jabiru",
        "Marabou stork",
        "Greater adjutant",
        "Australian white ibis",
        "Black-faced ibis",
        "Scarlet ibis",
        "Glossy ibis",
        "Eurasian spoonbill",
        "Roseate spoonbill",
        "White-crested tiger heron",
        "Eurasian bittern",
        "Rufescent tiger heron",
        "Little bittern",
        "Boat-billed heron",
        "Black-crowned night heron",
        "Green heron",
        "Squacco heron",
        "Cattle egret",
        "Grey heron",
        "Goliath heron",
        "Great blue heron",
        "Striated heron",
        "Little egret",
        "Red-billed tropicbird",
        "White-tailed tropicbird",
        "Great frigatebird",
        "Christmas frigatebird",
        "Hammerkop",
        "Great white pelican",
        "Shoebill",
        "Australian pelican",
        "Brown pelican",
        "American white pelican",
        "Northern gannet",
        "Australasian gannet",
        "Masked booby",
        "Blue-footed booby",
        "Peruvian booby",
        "Pygmy cormorant",
        "Flightless cormorant",
        "Double-crested cormorant",
        "European shag",
        "Guanay cormorant",
        "Great cormorant",
        "Anhinga",
        "Imperial shag",
        "Turkey vulture",
        "King vulture",
        "Black vulture",
        "California condor",
        "Andean condor",
        "Northern crested caracara",
        "Pygmy falcon",
        "Common kestrel",
        "Yellow-headed caracara",
        "Laughing falcon",
        "Greater kestrel",
        "Merlin",
        "American kestrel",
        "Eurasian hobby",
        "Lanner falcon",
        "Gyrfalcon",
        "Prairie falcon",
        "Peregrine falcon",
        "Secretarybird",
        "Osprey",
        "European honey buzzard",
        "Swallow-tailed kite",
        "Snail kite",
        "Mississippi kite",
        "Red kite",
        "White-tailed eagle",
        "Black kite",
        "Brahminy kite",
        "African fish eagle",
        "Bald eagle",
        "Palm-nut vulture",
        "Bearded vulture",
        "Steller's sea eagle",
        "Egyptian vulture",
        "White-backed vulture",
        "Indian vulture",
        "Griffon vulture",
        "Rüppell's vulture",
        "Lappet-faced vulture",
        "Black-chested snake eagle",
        "Crested serpent eagle",
        "Western marsh harrier",
        "Bateleur",
        "Pied harrier",
        "African harrier-hawk",
        "Northern harrier",
        "Lizard buzzard",
        "Spotted harrier",
        "Grey goshawk",
        "Dark chanting goshawk",
        "Little sparrowhawk",
        "Besra",
        "Eurasian sparrowhawk",
        "Cooper's hawk",
        "Northern goshawk",
        "Grasshopper buzzard",
        "Crane hawk",
        "Plumbeous hawk",
        "Common black hawk",
        "Savanna hawk",
        "White hawk",
        "Harris' hawk",
        "Black-collared hawk",
        "Solitary eagle",
        "Red-shouldered hawk",
        "Swainson's hawk",
        "Galápagos hawk",
        "Zone-tailed hawk",
        "Red-tailed hawk",
        "Common buzzard",
        "Ferruginous hawk",
        "Long-legged buzzard",
        "Harpy eagle",
        "Philippine eagle",
        "Crested eagle",
        "Indian black eagle",
        "Greater spotted eagle",
        "Eastern imperial eagle",
        "Golden eagle",
        "Wedge-tailed eagle",
        "Verreaux's eagle",
        "Wahlberg's eagle",
        "Black-and-white hawk-eagle",
        "Martial eagle",
        "Philippine hawk-eagle",
        "Crowned eagle",
        "Great bustard",
        "Kori bustard",
        "Australian bustard",
        "Northern black korhaan",
        "Little bustard",
        "Houbara bustard",
        "Kagu",
        "Subdesert mesite",
        "Red-legged seriema",
        "Sunbittern",
        "Corn crake",
        "Okinawa rail",
        "Virginia rail",
        "Buff-banded rail",
        "Water rail",
        "Baillon's crake",
        "Sora",
        "Purple swamphen",
        "Takahē",
        "Purple gallinule",
        "Common moorhen",
        "Eurasian coot",
        "Masked finfoot",
        "Pale-winged trumpeter",
        "African finfoot",
        "Limpkin",
        "Sungrebe",
        "Yellow-legged buttonquail",
        "Red-crowned crane",
        "Quail-plover",
        "Grey crowned crane",
        "Sarus crane",
        "Siberian crane",
        "Brolga",
        "Sandhill crane",
        "Common crane",
        "Whooping crane",
        "Eurasian stone-curlew",
        "Beach stone-curlew",
        "Snowy sheathbill",
        "Magellanic plover",
        "Eurasian oystercatcher",
        "Black oystercatcher",
        "Crab plover",
        "Black-winged stilt",
        "Ibisbill",
        "Banded stilt",
        "Pied avocet",
        "Red-necked avocet",
        "Blacksmith plover",
        "Northern lapwing",
        "Masked lapwing",
        "Southern lapwing",
        "Spur-winged lapwing",
        "European golden plover",
        "Grey plover",
        "American golden plover",
        "Ringed plover",
        "Kentish plover",
        "Inland plover",
        "Killdeer",
        "Wrybill",
        "Greater painted-snipe",
        "African jacana",
        "Pheasant-tailed jacana",
        "White-bellied seedsnipe",
        "American woodcock",
        "Jack snipe",
        "Common snipe",
        "Short-billed dowitcher",
        "Hudsonian godwit",
        "Bar-tailed godwit",
        "Eurasian curlew",
        "Whimbrel",
        "Long-billed curlew",
        "Common redshank",
        "Greater yellowlegs",
        "Wandering tattler",
        "Dunlin",
        "Spotted sandpiper",
        "Ruff",
        "Spoon-billed sandpiper",
        "Red knot",
        "Red-necked phalarope",
        "Egyptian plover",
        "Australian pratincole",
        "Cream-coloured courser",
        "Collared pratincole",
        "Grey gull",
        "Mew gull",
        "Herring gull",
        "Kelp gull",
        "Great black-backed gull",
        "Laughing gull",
        "Ivory gull",
        "Common black-headed gull",
        "Ross's gull",
        "Swallow-tailed gull",
        "Gull-billed tern",
        "Caspian tern",
        "Black-legged kittiwake",
        "Arctic tern",
        "Roseate tern",
        "Antarctic tern",
        "Sooty tern",
        "Black tern",
        "Brown noddy",
        "White tern",
        "Inca tern",
        "Black skimmer",
        "Long-tailed skua",
        "South polar skua",
        "Parasitic skua",
        "Great skua",
        "Atlantic puffin",
        "Little auk",
        "Guillemot",
        "Razorbill",
        "Black guillemot",
        "Rhinoceros auklet",
        "Crowned sandgrouse",
        "Lichtenstein's sandgrouse",
        "Pin-tailed sandgrouse",
        "Speckled pigeon",
        "Japanese wood pigeon",
        "Common pigeon",
        "Eurasian collared dove",
        "Wood pigeon",
        "Pink pigeon",
        "European turtle dove",
        "Namaqua dove",
        "Common bronzewing",
        "Spinifex pigeon",
        "Diamond dove",
        "Mourning dove",
        "Inca dove",
        "White-tipped dove",
        "Blue-headed quail-dove",
        "Key West quail-dove",
        "Nicobar pigeon",
        "Victoria crowned pigeon",
        "Luzon bleeding-heart",
        "African green pigeon",
        "Wompoo fruit dove",
        "Rose-crowned fruit dove",
        "Madagascar blue pigeon",
        "Superb fruit dove",
        "Green imperial pigeon",
        "Topknot pigeon",
        "New Zealand pigeon",
        "Mourning dove",
        "Kakapo",
        "Kea",
        "Vernal hanging parrot",
        "Palm cockatoo",
        "Red-tailed black cockatoo",
        "Gang-gang cockatoo",
        "Little corella",
        "Sulphur-crested cockatoo",
        "Galah",
        "Rainbow lorikeet",
        "Cockatiel",
        "Red lory",
        "Varied lorikeet",
        "Musk lorikeet",
        "Papuan lorikeet",
        "Bluebonnet",
        "Crimson rosella",
        "Red-crowned parakeet",
        "Mulga parrot",
        "Red-rumped parrot",
        "Rock parrot",
        "Budgerigar",
        "Red-capped parrot",
        "Blue-rumped parrot",
        "Blue-crowned racquet-tail",
        "Red-winged parrot",
        "Australian king parrot",
        "Blue-naped parrot",
        "Regent parrot",
        "Superb parrot",
        "Plum-headed parakeet",
        "Rose-ringed parakeet",
        "Rosy-faced lovebird",
        "Grey-headed lovebird",
        "Greater vasa parrot",
        "Eclectus parrot",
        "Grey parrot",
        "Rüppell's parrot",
        "Spix's macaw",
        "Blue-and-yellow macaw",
        "Scarlet macaw",
        "Red-and-green macaw",
        "Blue-winged macaw",
        "Peach-fronted parakeet",
        "Red-shouldered macaw",
        "Blue-crowned parakeet",
        "Hyacinth macaw",
        "Burrowing parakeet",
        "Reddish-bellied parakeet",
        "Monk parakeet",
        "Yellow-chevroned parakeet",
        "Blue-winged parrotlet",
        "Sapphire-rumped parrotlet",
        "Vulturine parrot",
        "Turquoise-fronted amazon",
        "Cuban amazon",
        "Blue-headed parrot",
        "Yellow-crowned amazon",
        "Red-fan parrot",
        "Double-eyed fig parrot",
        "Hoatzin",
        "Green turaco",
        "Red-crested turaco",
        "Purple-crested turaco",
        "Fischer's turaco",
        "Grey go-away-bird",
        "Great blue turaco",
        "Jacobin cuckoo",
        "Great spotted cuckoo",
        "Common hawk-cuckoo",
        "Common cuckoo",
        "Lesser cuckoo",
        "Brush cuckoo",
        "African emerald cuckoo",
        "Horsfield's bronze cuckoo",
        "Channel-billed cuckoo",
        "Asian koel",
        "Squirrel cuckoo",
        "Giant coua",
        "Pheasant coucal",
        "White-browed coucal",
        "Groove-billed ani",
        "Guira cuckoo",
        "Pheasant cuckoo",
        "Greater roadrunner",
        "Australian masked owl",
        "Barn owl",
        "Eastern screech owl",
        "Sokoke scops owl",
        "Eurasian scops owl",
        "Southern white-faced owl",
        "Great horned owl",
        "Verreaux's eagle-owl",
        "Eurasian eagle-owl",
        "Snowy owl",
        "Blakiston's fish owl",
        "Pel's fishing owl",
        "Great grey owl",
        "Tawny owl",
        "Ural owl",
        "Crested owl",
        "Barred owl",
        "Spectacled owl",
        "Northern hawk-owl",
        "Mountain pygmy owl",
        "Ferruginous pygmy owl",
        "African barred owlet",
        "Long-whiskered owlet",
        "Little owl",
        "Elf owl",
        "Northern saw-whet owl",
        "Burrowing owl",
        "Southern boobook",
        "Jamaican owl",
        "Long-eared owl",
        "Papuan hawk-owl",
        "Short-eared owl",
        "Scops owl",
        "Tawny frogmouth",
        "Oilbird",
        "Common potoo",
        "Common nighthawk",
        "Australian owlet-nightjar",
        "Pauraque",
        "Common poorwill",
        "Chuck-will's-widow",
        "Whip-poor-will",
        "Silky-tailed nightjar",
        "European nightjar",
        "Golden nightjar",
        "Long-trained nightjar",
        "Standard-winged nightjar",
        "Abyssinian nightjar",
        "Waterfall swift",
        "Cave swiftlet",
        "Edible-nest swiftlet",
        "White-throated needletail",
        "White-rumped needletail",
        "Pygmy swift",
        "Chimney swift",
        "Alpine swift",
        "Common swift",
        "White-tipped sicklebill",
        "Scale-throated hermit",
        "Eastern long-tailed hermit",
        "Planalto hermit",
        "Violet sabrewing",
        "Swallow-tailed hummingbird",
        "Crimson topaz",
        "Ruby topaz",
        "Plovercrest",
        "Frilled coquette",
        "Rufous-crested coquette",
        "Red-billed streamertail",
        "Violet-capped woodnymph",
        "Collared inca",
        "Ecuadorian hillstar",
        "Versicoloured emerald",
        "Giant hummingbird",
        "Sword-billed hummingbird",
        "White-throated hummingbird",
        "Speckled hummingbird",
        "Violet-fronted brilliant",
        "Greenish puffleg",
        "Black-tailed trainbearer",
        "Bee hummingbird",
        "Long-tailed sylph",
        "Ruby-throated hummingbird",
        "Anna's hummingbird",
        "Pallid swift",
        "Speckled mousebird",
        "Blue-naped mousebird",
        "Narina trogon",
        "Red-headed",
        "Black-throated trogon",
        "Resplendent quetzal",
        "Elegant trogon",
        "Cuban trogon",
        "European roller",
        "Racquet-tailed roller",
        "Indian roller",
        "Common paradise kingfisher",
        "Scaly ground roller",
        "Dollarbird",
        "Laughing kookaburra",
        "Cuckoo-roller",
        "Stork-billed kingfisher",
        "Collared kingfisher",
        "Sacred kingfisher",
        "Grey-headed kingfisher",
        "Ruddy kingfisher",
        "Yellow-billed kingfisher",
        "African pygmy kingfisher",
        "Common kingfisher",
        "Little kingfisher",
        "Green kingfisher",
        "Ringed kingfisher",
        "Belted kingfisher",
        "Pied kingfisher",
        "Cuban tody",
        "Jamaican tody",
        "Blue-crowned motmot",
        "Rufous-capped motmot",
        "Turquoise-browed motmot",
        "Red-bearded bee-eater",
        "Swallow-tailed bee-eater",
        "European bee-eater",
        "Rainbow bee-eater",
        "Southern carmine bee-eater",
        "Eurasian hoopoe",
        "Southern yellow-billed hornbill",
        "Green wood hoopoe",
        "Red-billed hornbill",
        "African pied hornbill",
        "Common scimitarbill",
        "Indian grey hornbill",
        "Great hornbill",
        "Rhinoceros hornbill",
        "Walden's hornbill",
        "Trumpeter hornbill",
        "Southern ground hornbill",
        "Emerald toucanet",
        "Chestnut-eared aracari",
        "Groove-billed toucanet",
        "Fiery-billed aracari",
        "Collared aracari",
        "Spot-billed toucanet",
        "Plate-billed mountain toucan",
        "Toco toucan",
        "Keel-billed toucan",
        "Green-billed toucan",
        "Black-spotted barbet",
        "Fire-tufted barbet",
        "Red-throated barbet",
        "Coppersmith barbet",
        "Yellow-fronted tinkerbird",
        "Bearded barbet",
        "Black-collared barbet",
        "Red-and-yellow barbet",
        "Greater honeyguide",
        "Eurasian wryneck",
        "Ochre-collared piculet",
        "Guianan piculet",
        "Rufous piculet",
        "Acorn woodpecker",
        "Red-headed woodpecker",
        "Yellow-fronted woodpecker",
        "Gila woodpecker",
        "Yellow-bellied sapsucker",
        "Red-breasted sapsucker",
        "Nubian woodpecker",
        "Ground woodpecker",
        "Green-backed woodpecker",
        "Cardinal woodpecker",
        "Japanese pygmy woodpecker",
        "Great spotted woodpecker",
        "Hairy woodpecker",
        "Downy woodpecker",
        "Eurasian three-toed woodpecker",
        "Yellow-browed woodpecker",
        "Golden-olive woodpecker",
        "Northern flicker",
        "Campo flicker",
        "Chestnut woodpecker",
        "Lineated woodpecker",
        "Black woodpecker",
        "Greater yellownape",
        "Japanese woodpecker",
        "European green woodpecker",
        "Black-rumped flameback",
        "Orange-backed woodpecker",
        "Great slaty woodpecker",
        "Greater flameback",
        "Rufous-tailed jacamar",
        "Bluish-fronted jacamar",
        "Great jacamar",
        "White-necked puffbird",
        "Black-fronted nunbird",
        "White-eared puffbird",
        "Rusty-breasted nunlet",
        "Swallow-winged puffbird",
        "Lesser spotted woodpecker"
    ]

    static String name(int i) {
        int bird = i % NON_PASSERINES.size()
        NON_PASSERINES[bird]
    }

    static String type(int i) {
        name(i).split(' ')[-1]
    }

}
